name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Show Xcode version
      run: xcodebuild -version

    - name: Set Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.0.app

    - name: Check project.pbxproj file
      run: |
        ls -l HabitTracker.xcodeproj/project.pbxproj
        head -20 HabitTracker.xcodeproj/project.pbxproj

    - name: Build app
      run: |
        xcodebuild clean build \
          -scheme HabitTracker \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY=""
